# Cours de ia predilective

In [2]:
#!pip3 install torch torchvision

In [3]:
!where pip
import sys
sys.executable

c:\Users\mhmt_.000\Documents\Projet_IIM\cours_ai_a4\.venv\Scripts\pip.exe
C:\Python312\Scripts\pip.exe
C:\Python311\Scripts\pip.exe


'c:\\Users\\mhmt_.000\\Documents\\Projet_IIM\\cours_ai_a4\\.venv\\Scripts\\python.exe'

In [4]:
import numpy as np

In [5]:
import torch 

In [6]:
#data= [[1,2], [3,4]]

In [7]:
#x_data.size()

In [8]:
#x_data = torch.tensor(data)
#x_data

In [9]:
#np_array = np.array(data)


In [10]:
w = torch.tensor([2.0], requires_grad=True)
b = torch.tensor([1.0], requires_grad=True)
x = torch.tensor([3.0])

In [11]:
y_pred = w*x+b
print("y_pred:", y_pred.item())

y_pred: 7.0


In [12]:
y_true = torch.tensor([10.0])
loss= (y_pred - y_true)**2
print("Loss:", loss.item())

Loss: 9.0


In [13]:
print("Avant backward: w.grad =", {w.grad})

Avant backward: w.grad = {None}


In [14]:
loss.backward()

In [15]:
print("Après backward: w.grad =", {w.grad})
print("Après backward: b.grad =", {b.grad})

Après backward: w.grad = {tensor([-18.])}
Après backward: b.grad = {tensor([-6.])}


In [16]:
#update manuel des poids
learning_rate = 0.01
with torch.no_grad(): #désactive le suivi des gradients pour les opérations de mise à jour w=w+alpha*x
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad

In [17]:
print("Nouveaux paramètres: w =", w, ", b =", b)

Nouveaux paramètres: w = tensor([2.1800], requires_grad=True) , b = tensor([1.0600], requires_grad=True)


In [18]:
# Réinitialiser les gradients !! Important
w.grad.zero_()
b.grad.zero_()
print("Après remise à zéro: w.grad =", w.grad, ", b.grad =", b.grad)

Après remise à zéro: w.grad = tensor([0.]) , b.grad = tensor([0.])


In [19]:
import torch.nn as nn

percepton = nn.Linear(1, 1)

#voir les poids initiaux
print("poids:", percepton.weight)
print("biais : ", percepton.bias)

poids: Parameter containing:
tensor([[0.4073]], requires_grad=True)
biais :  Parameter containing:
tensor([0.8019], requires_grad=True)


In [20]:
#valeur de input x
#forward
x = torch.tensor([[3.0]]) # Shape (batch_size, features)
print("input:", x)
y_pred = percepton(x)
print(y_pred)

input: tensor([[3.]])
tensor([[2.0239]], grad_fn=<AddmmBackward0>)


### théoreme centrale de limite (?)

In [21]:
#Loss
y_true = torch.tensor([10.0])
criterion = nn.MSELoss()
loss = criterion(y_pred, y_true)

c:\Users\mhmt_.000\Documents\Projet_IIM\cours_ai_a4\.venv\Lib\site-packages\torch\nn\modules\loss.py:634: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [22]:
loss.backward()

In [23]:
print("Gradient du pois =", percepton.weight.grad)
print("Gradient du biais =", percepton.bias.grad)

Gradient du pois = tensor([[-47.8568]])
Gradient du biais = tensor([-15.9523])


###### pour la partie de en haut j'ai pas eu les meme res que le prof

In [24]:
import torch.optim as optim
optimizer = optim.SGD(percepton.parameters(), lr=0.01)

In [25]:
optimizer.step() #met à jour les poids automatiquement

In [26]:
print("Nouveaux poids:", percepton.weight, "Nouveau biais:", percepton.bias)

Nouveaux poids: Parameter containing:
tensor([[0.8859]], requires_grad=True) Nouveau biais: Parameter containing:
tensor([0.9614], requires_grad=True)


###### pour la partie de en haut j'ai pas eu les meme res que le prof

#### On va créer des models de neuronnes

In [27]:
class SimpleNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 4)
        self.fc2 = nn.Linear(4, 3)
        self.fc3 = nn.Linear(3, 1)
        self.relu = nn.ReLU()
        self.sigmoid= nn.Sigmoid()

    def forward(self, x): 
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.fc3(x)
        x = self.sigmoid(x)
        return x


In [28]:
model = SimpleNet()

In [29]:
model

SimpleNet(
  (fc1): Linear(in_features=2, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=3, bias=True)
  (fc3): Linear(in_features=3, out_features=1, bias=True)
  (relu): ReLU()
  (sigmoid): Sigmoid()
)

In [30]:
x = torch.tensor([1.0, 2.0])
y = torch.tensor([5.0])
y_pred = model(x)
loss = nn.MSELoss()(y_pred, y)

loss.backward()

In [31]:
# !pip3 install matplotlib

In [32]:
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Compose, Normalize
import matplotlib.pyplot as plt

In [33]:
training_data = datasets.MNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)
test_data = datasets.MNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

In [34]:
training_dataloader = DataLoader(training_data, batch_size=64, shuffle=True, pin_memory=True, num_workers=4)
test_dataloader = DataLoader(test_data, batch_size=64, shuffle=False, pin_memory=True, num_workers=4)

In [35]:
print(training_data.classes)
print(training_data.data.size())

['0 - zero', '1 - one', '2 - two', '3 - three', '4 - four', '5 - five', '6 - six', '7 - seven', '8 - eight', '9 - nine']
torch.Size([60000, 28, 28])


In [36]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.fc = nn.Sequential(
            nn.Linear(28*28, 512), # taille image (28*28) 512
            nn.ReLU(),
            nn.Linear(512, 128), # 512 - 128
            nn.ReLU(),
            nn.Linear(128, 10), # 128
        )
        
    def forward(self, x):
        x = self.flatten(x)
        logits = self.fc(x)
        return logits

In [37]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (fc): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=128, bias=True)
    (3): ReLU()
    (4): Linear(in_features=128, out_features=10, bias=True)
  )
)


In [38]:
x=torch.rand(1,28,28,device=device)
logits=model(x)

In [39]:
logits

tensor([[ 0.1029,  0.0463, -0.0094,  0.0880,  0.0080, -0.0595,  0.0955,  0.0784,
         -0.1254,  0.0298]], grad_fn=<AddmmBackward0>)

In [40]:
pred_probab = nn.Softmax(dim=1)(logits)
pred_probab

tensor([[0.1078, 0.1019, 0.0963, 0.1062, 0.0980, 0.0916, 0.1070, 0.1052, 0.0858,
         0.1002]], grad_fn=<SoftmaxBackward0>)

In [41]:
loss_fn= nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

In [42]:
#pf tips
tuple_tets = (1,2,"a")
a,b,c = tuple_tets
print()

In [43]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch_idx, batch_value in enumerate(dataloader): 
        X, y = batch_value
        X, y = X.to(device), y.to(device)

        # Forward pass
        pred = model(X)
        loss = loss_fn(pred, y)

        # Background pass
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()


        if batch_idx % 100 == 0:
            loss, current = loss.item(), (batch_idx+1) * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [44]:
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0 
    with torch.no_grad():
        for X, y in dataloader :
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss+= loss_fn(pred, y).item()
            correct+= (pred.argmax(1)==y).type(torch.float).sum().item()

    test_loss/= num_batches
    correct/= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [50]:
epochs = 55
for t in range(epochs):
    print(f"Epochs {t+1}\n-------------------------------")
    train(training_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)
print("Done!")


Epochs 1
-------------------------------


c:\Users\mhmt_.000\Documents\Projet_IIM\cours_ai_a4\.venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)


loss: 0.332087  [   64/60000]
loss: 0.239848  [ 6464/60000]
loss: 0.377270  [12864/60000]
loss: 0.576638  [19264/60000]
loss: 0.306497  [25664/60000]
loss: 0.178224  [32064/60000]
loss: 0.116953  [38464/60000]
loss: 0.190186  [44864/60000]
loss: 0.149747  [51264/60000]
loss: 0.339604  [57664/60000]
Test Error: 
 Accuracy: 92.2%, Avg loss: 0.271040 

Epochs 2
-------------------------------
loss: 0.144804  [   64/60000]
loss: 0.131037  [ 6464/60000]
loss: 0.317378  [12864/60000]
loss: 0.252306  [19264/60000]
loss: 0.230124  [25664/60000]
loss: 0.260437  [32064/60000]
loss: 0.365137  [38464/60000]
loss: 0.384286  [44864/60000]
loss: 0.205964  [51264/60000]
loss: 0.251803  [57664/60000]
Test Error: 
 Accuracy: 92.2%, Avg loss: 0.269239 

Epochs 3
-------------------------------
loss: 0.257635  [   64/60000]
loss: 0.234232  [ 6464/60000]
loss: 0.414024  [12864/60000]
loss: 0.193989  [19264/60000]
loss: 0.314221  [25664/60000]
loss: 0.303291  [32064/60000]
loss: 0.240213  [38464/60000]
loss

##### pythorch tutoriel : https://docs.pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html

In [46]:
#!pip3 install --upgrade onnx onnxscript

In [52]:
example_inputs = (torch.randn(1, 1, 28, 28),)
model.to("cpu")
onnx_program = torch.onnx.export(model, example_inputs, dynamo=True)
onnx_program.save("model3.onnx")

[torch.onnx] Obtain model graph for `NeuralNetwork([...]` with `torch.export.export(..., strict=False)`...
[torch.onnx] Obtain model graph for `NeuralNetwork([...]` with `torch.export.export(..., strict=False)`... ✅
[torch.onnx] Run decomposition...
[torch.onnx] Run decomposition... ✅
[torch.onnx] Translate the graph into ONNX...
[torch.onnx] Translate the graph into ONNX... ✅


##### html ccs js githubpage onnxruntime
créer un canva, recup la taille, transfor le canva en tensor onnx coté js etc etc

###### email du prof : nathan.vidal@ext.devinci.fr